export interface Job {
  id: number;
  slug: string;
  department: string;
  title: string;
  location: string;
  type: string;
  aboutRole: string;
  responsibilities: string[];
  requirements: string[];
}

export const jobListings: Job[] = [
  {
    id: 1,
    slug: 'fullstack-developer',
    department: 'Engineering',
    title: 'Fullstack Developer (React/Node.js)',
    location: 'Remote',
    type: 'Full-Time',
    aboutRole: 'As a Fullstack Developer at ValarPay, you will be instrumental in building and scaling the next generation of borderless financial infrastructure. You will work closely with product managers and designers to deliver seamless user experiences, from the React frontend down to our high-performance Node.js backend services.',
    responsibilities: [
      'Design, build, and maintain efficient, reusable, and reliable React components.',
      'Develop robust RESTful and GraphQL APIs using Node.js and TypeScript.',
      'Collaborate with the design team to implement pixel-perfect user interfaces.',
      'Optimize application performance for maximum speed and scalability.',
      'Participate in code reviews, automated testing, and CI/CD pipeline improvements.',
    ],
    requirements: [
      '3+ years of professional experience as a Fullstack Developer.',
      'Deep understanding of React.js, Next.js, and modern state management.',
      'Strong proficiency in Node.js, Express, and REST/GraphQL architecture.',
      'Experience with PostgreSQL, Redis, and ORMs (Prisma/TypeORM).',
      'Solid understanding of web security principles and secure coding practices.',
      'Excellent communication skills in a remote-first environment.',
    ]
  },
  {
    id: 2,
    slug: 'security-engineer',
    department: 'Engineering',
    title: 'Security Engineer',
    location: 'Remote',
    type: 'Full-Time',
    aboutRole: 'Security is the foundation of ValarPay. As a Security Engineer, you will be responsible for safeguarding our infrastructure, applications, and user data against evolving threats. You will lead penetration testing, security audits, and work directly with engineering teams to embed security into the CI/CD pipeline.',
    responsibilities: [
      'Conduct regular security assessments, penetration testing, and vulnerability scanning.',
      'Design and implement robust security architecture for cloud-native applications (AWS/GCP).',
      'Monitor systems for suspicious activity and respond to security incidents.',
      'Educate and mentor engineering teams on secure coding practices.',
      'Ensure compliance with international security standards (PCI-DSS, ISO 27001).',
    ],
    requirements: [
      '4+ years of experience in Application Security or Infrastructure Security.',
      'Strong knowledge of common web vulnerabilities (OWASP Top 10) and mitigation strategies.',
      'Experience with cloud security (AWS/GCP), IAM, and container security (Kubernetes).',
      'Proficiency in at least one scripting language (Python, Go, or Node.js).',
      'Relevant security certifications (OSCP, CISSP, AWS Security) are a plus.',
      'Ability to thrive in a fast-paced fintech environment.',
    ]
  },
  {
    id: 3,
    slug: 'aml-kyc-compliance-officer',
    department: 'Compliance',
    title: 'AML & KYC Compliance Officer',
    location: 'Remote',
    type: 'Full-Time',
    aboutRole: 'The AML & KYC Compliance Officer is critical to ensuring ValarPay operates within regulatory frameworks while preventing financial crime. You will manage the day-to-day operations of our Anti-Money Laundering (AML) and Know Your Customer (KYC) programs, investigating suspicious activities and ensuring compliance with local and global regulations.',
    responsibilities: [
      'Review and analyze customer profiles during the onboarding process to ensure KYC compliance.',
      'Investigate alerts generated by transaction monitoring systems for suspicious activity.',
      'File Suspicious Activity Reports (SARs) with relevant regulatory authorities.',
      'Stay updated on regulatory changes in Nigeria and key international markets.',
      'Assist in the development and implementation of new compliance policies and training.',
    ],
    requirements: [
      '3+ years of experience in AML/KYC compliance within the banking or fintech sector.',
      'Deep understanding of CBN (Central Bank of Nigeria) regulations and global AML laws.',
      'Strong analytical skills with extreme attention to detail.',
      'Experience using modern transaction monitoring and identity verification tools.',
      'Excellent written and verbal communication skills.',
      'Ability to handle sensitive information with the utmost integrity and confidentiality.',
    ]
  }
];

export const getJobBySlug = (slug: string) => {
  return jobListings.find(job => job.slug === slug);
};
